### ISSUE TITLE
replace all raw-pointers/allocations in WNScript.g with make_unique.

### ISSUE THREAD

**Issue by AWoloszyn** [WNProject/WNFramework#38]
Too many raw pointers flying around. Should be able to use the new memory::make_unique, and change ALL raw pointer constructors to memory::unqiue_ptr<>&&.

**Comment by devpow112** [comment]
Was this done?

**Comment by AWoloszyn** [comment]
Much of this was done. Not all of it, but it looks like I cannot get the last little bit of it done. ANTLR won't let me move out the pointer. Once everything makes it into the tree, it all lives in unique_ptrs.
