### ISSUE TITLE
Add "Semaphores" to graphics

### ISSUE THREAD

**Issue by AWoloszyn** [WNProject/WNFramework#71]
We currently use a Fence for everything, but that is overkill in a lot of cases.
We need something akin to VkSemaphore (i.e. device/device synchronization that does not modify the host behavior).

This should be reasonably easy to add. Just a new type, but should improve performance and prevent blocking as much.

**Comment by devpow112** [comment]
Added in 154fcdb9e09c104b2adc1944bfa925b46d4086dc
