### ISSUE TITLE
Add a filesystem backed mapping type the is based on a directory.

### ISSUE THREAD

**Issue by AWoloszyn** [WNProject/WNFramework#73]
Right now we have "scratch" which creates a temporary directory, and memory_backed which keeps everything in memory. We should create a file_system_backed mapping that just roots the mapping in a directory.

**Comment by devpow112** [comment]
I'm on it!!!!!!!!

**Comment by devpow112** [comment]
Fixed in 692074643978bfec6b3ec898ba95411a7c56158b
