### ISSUE TITLE
Turn off error dialog pop-ups in windows.

### ISSUE THREAD

**Issue by AWoloszyn** [WNProject/WNFramework#99]
If we hit an internal error (Example, an incorrect use of the STL), the MSVCRT will pop up a dialog. Turn this off, since it hangs our build-bots. It would be better to just crash, then we can investigate.

**Comment by devpow112** [comment]
We can add this in out testing entry point or a lower entry point

if( !IsDebuggerPresent() )
{
  _CrtSetReportMode( _CRT_ASSERT, _CRTDBG_MODE_FILE | _CRTDBG_MODE_DEBUG );
  _CrtSetReportFile( _CRT_ASSERT, _CRTDBG_FILE_STDERR );
}

**Comment by devpow112** [comment]
Fixed in b9302bfa18edad849d4a65121ec5a00fb9e279d8

**Comment by devpow112** [comment]
Issue still present additional fix being worked on

**Comment by devpow112** [comment]
Use this: https://github.com/dotnet/llilc/issues/584

**Comment by devpow112** [comment]
Take two, fixed in ff4d56d6ca42878a000e81396958d52ee95a548f
